""" schema.py 
Appwrite collection schemas matching the four analytics CSV tables."""

SCHEMA_DEFINITIONS = {
    "matches": {
        "description": "Equivalent to matches.csv",
        "attributes": [
            {"name": "match_id", "type": "string", "size": 64, "required": True},
            {"name": "date", "type": "string", "size": 32, "required": False},
            {"name": "city", "type": "string", "size": 128, "required": False},
            {"name": "venue", "type": "string", "size": 255, "required": False},
            {"name": "team1", "type": "string", "size": 128, "required": True},
            {"name": "team2", "type": "string", "size": 128, "required": True},
            {"name": "winner", "type": "string", "size": 128, "required": False},
            {"name": "win_by", "type": "string", "size": 32, "required": False},
            {"name": "win_margin", "type": "integer", "required": False},
            {"name": "event_name", "type": "string", "size": 255, "required": False},
            {"name": "event_stage", "type": "string", "size": 128, "required": False},
            {"name": "match_type", "type": "string", "size": 32, "required": False},
            {"name": "gender", "type": "string", "size": 16, "required": False},
            {"name": "toss_winner", "type": "string", "size": 128, "required": False},
            {"name": "toss_decision", "type": "string", "size": 32, "required": False},
            {"name": "player_of_match", "type": "string", "size": 128, "required": False},
            {"name": "season", "type": "string", "size": 32, "required": False},
            {"name": "overs", "type": "integer", "required": False},
        ],
        "indexes": [
            {"key": "idx_match_id", "type": "key", "attributes": ["match_id"]},
            {"key": "idx_date", "type": "key", "attributes": ["date"]},
            {"key": "idx_team1", "type": "key", "attributes": ["team1"]},
            {"key": "idx_team2", "type": "key", "attributes": ["team2"]},
            {"key": "idx_city", "type": "key", "attributes": ["city"]},
        ],
    },
    "deliveries": {
        "description": "Equivalent to deliveries.csv",
        "attributes": [
            {"name": "match_id", "type": "string", "size": 64, "required": True},
            {"name": "innings", "type": "integer", "required": True},
            {"name": "over", "type": "integer", "required": True},
            {"name": "ball", "type": "integer", "required": True},
            {"name": "batter", "type": "string", "size": 128, "required": False},
            {"name": "bowler", "type": "string", "size": 128, "required": False},
            {"name": "non_striker", "type": "string", "size": 128, "required": False},
            {"name": "batter_runs", "type": "integer", "required": True},
            {"name": "extras", "type": "integer", "required": True},
            {"name": "total_runs", "type": "integer", "required": True},
            {"name": "extras_type", "type": "string", "size": 64, "required": False},
            {"name": "wicket_type", "type": "string", "size": 64, "required": False},
            {"name": "player_dismissed", "type": "string", "size": 128, "required": False},
        ],
        "indexes": [
            {"key": "idx_match_id", "type": "key", "attributes": ["match_id"]},
            {"key": "idx_batter", "type": "key", "attributes": ["batter"]},
            {"key": "idx_bowler", "type": "key", "attributes": ["bowler"]},
        ],
    },
    "batting": {
        "description": "Equivalent to batting.csv",
        "attributes": [
            {"name": "match_id", "type": "string", "size": 64, "required": True},
            {"name": "innings", "type": "integer", "required": True},
            {"name": "batter", "type": "string", "size": 128, "required": True},
            {"name": "team", "type": "string", "size": 128, "required": False},
            {"name": "runs", "type": "integer", "required": True},
            {"name": "balls_faced", "type": "integer", "required": True},
            {"name": "fours", "type": "integer", "required": True},
            {"name": "sixes", "type": "integer", "required": True},
            {"name": "strike_rate", "type": "double", "required": True},
            {"name": "is_out", "type": "integer", "required": True},
            {"name": "dismissal_kind", "type": "string", "size": 64, "required": False},
        ],
        "indexes": [
            {"key": "idx_match_id", "type": "key", "attributes": ["match_id"]},
            {"key": "idx_batter", "type": "key", "attributes": ["batter"]},
            {"key": "idx_team", "type": "key", "attributes": ["team"]},
        ],
    },
    "bowling": {
        "description": "Equivalent to bowling.csv",
        "attributes": [
            {"name": "match_id", "type": "string", "size": 64, "required": True},
            {"name": "innings", "type": "integer", "required": True},
            {"name": "bowler", "type": "string", "size": 128, "required": True},
            {"name": "team", "type": "string", "size": 128, "required": False},
            {"name": "overs", "type": "string", "size": 16, "required": True},
            {"name": "deliveries", "type": "integer", "required": True},
            {"name": "legal_deliveries", "type": "integer", "required": True},
            {"name": "runs_conceded", "type": "integer", "required": True},
            {"name": "wickets", "type": "integer", "required": True},
            {"name": "economy", "type": "double", "required": True},
            {"name": "extras_given", "type": "integer", "required": True},
        ],
        "indexes": [
            {"key": "idx_match_id", "type": "key", "attributes": ["match_id"]},
            {"key": "idx_bowler", "type": "key", "attributes": ["bowler"]},
            {"key": "idx_team", "type": "key", "attributes": ["team"]},
        ],
    },
}
